name: Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: echo "Deploying to production..."
    - run: docker build . -t sasikiran06/fastapi-application
    - run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - run: docker push sasikiran06/fastapi-application:latest
    